version: '3.3'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: mongo
    network_mode: host

  customerservice:
    image: customer-image1
    build: ./
    ports:
      - 8083:8083
    restart: always
    depends_on:
      - mongo
    network_mode: host
